### ISSUE TITLE
Typo in URL https:/docs.joy.id in repo https://github.com/nervina-labs/joyid-docs

### ISSUE THREAD

**Issue by hboon** [nervina-labs/joyid-docs#11]
Should be `https://docs.joy.id` instead

<img width="216" alt="Screenshot 2023-05-02 at 12 10 02 PM" src="https://user-images.githubusercontent.com/56189/235577600-698f91bf-fbf5-4263-9821-9da191bc1a26.png">

**Comment by duanyytop** [comment]
Fixed. Thanks
