### ISSUE TITLE
[Document Enhancement] Security model from the user's point of view.

### ISSUE THREAD

**Issue by alejandroRbit** [nervina-labs/joyid-docs#14]
As a member of the community I like to recommend JoyID to other members (common users, such as holders) to know their opinion about the application. Basically it's so easy to use that it feels like it's not secure. Therefore the biggest source of doubts in the community is about security.

- How does it work?
- How are the keys managed?
- How can the keys be recovered if necessary?
- Can the keys be extracted from the secure enclave?
- Is social recovery safe enough?
- What is the difference between the secure enclave and the secure element that Ledger uses?

These are just some of the questions that users have asked me when trying JoyID. One of the conclusions they usually draw is that they would use it for small amounts, as you would use a physical wallet today, and not for large amounts, such as a bank account.

I think this topic is very important and especially after what we have experienced in the space with Ledger recently, where it was supposed to be impossible to extract the keys from the secure element of the device, and the reaction of the community to this event.

I understand the goal is mass adoption and expanding the user base as much as possible, which is great, but a significant portion of the current user base has shown that they still prioritize security over comfort or convenience when it comes to use of wallets.

Finally, having a complete documentation in this regard will help you a lot with user support, reducing the workload, which is a great advantage.

**Comment by yuche** [comment]
We have just updated our website with a number of frequently asked questions:

https://joy.id/faqs

**Comment by alejandroRbit** [comment]
Great! Thank you so much!
