### ISSUE TITLE
NFT detail URL is broken on the CKB Sign CoTA page.

### ISSUE THREAD

**Issue by jordanmack** [nervina-labs/joyid-docs#31]
On the [CKB Sign CoTA page](https://docs.joyid.dev/guide/ckb/sign-cota) it says:

```
Once the NFTs are claimed to your JoyID account, you can visit NFT list in JoyID App. You can click any NFT to visit NFT detail page and the page URL is like this:

https://testnet.joyid.dev/nft/ffffffff003688bb1cba009d89dd3f1c8a6027a0c5851e860000002e
```

This URL does not work and no NFT is visible. Even if this is just for the demonstration of the URL structure, a functional link would be much more helpful.

I have updated this page in #28, however, this URL is still present even though it does not work properly.

**Comment by duanyytop** [comment]
Thanks for your feedback and we will update the link in https://github.com/nervina-labs/joyid-docs/pull/33/commits/15b90c6737167aafc2afc2e4bd469ecadd018cf4
