### ISSUE TITLE
Add the mainnet and testnet deployment info to the documentation.

### ISSUE THREAD

**Issue by jordanmack** [nervina-labs/joyid-docs#41]
I'd recommend adding the mainnet and testnet deployment info to the documentation somewhere. I found it in the JoyID SDK source, but it is not obvious since it is not under Nervina Labs' main GitHub.

https://github.com/duanyytop/joyid-sdk-js/blob/develop/src/constants/index.ts

**Comment by duanyytop** [comment]
We have added the JoyID contract deplyment to the `joyid-sdk-js` README and you can see the detail: https://github.com/nervina-labs/joyid-sdk-js/tree/main/packages/ckb#joyid-contract-deployment

**Comment by duanyytop** [comment]
We have added the JoyID smart contract to the JoyID document website and the related Pull Request is [here](https://github.com/nervina-labs/joyid-docs/pull/43).  cc @jordanmack
